tms/devices/urls.py
# Django
from django.urls import path
# Local
from devices import views

app_name = 'devices'
urlpatterns = [
    path('', views.DeviceIndex.as_view(), name='device_overview'),
    path('device/<int:pk>', views.DeviceDetailView.as_view(), name='device_detail'),
    path('device/create/', views.DeviceCreateView.as_view(), name='create_device'),
    path('device/<int:pk>/update', views.DeviceUpdateView.as_view(), name='update_device'),
    path('device/<int:pk>/read', views.DeviceReadView.as_view(), name='read_device'),
    path('device/<int:pk>/delete', views.DeviceDeleteView.as_view(), name='delete_device')
]

tms/tms/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('news/', include('news.urls')),
    path('news/', include('django.contrib.auth.urls')),
    path('test_cases/', include('test_cases.urls')),
    path('test_cases/', include('django.contrib.auth.urls')),
    path('device/', include('devices.urls')),
    path('device/', include('django.contrib.auth.urls')),
    path('project/', include('projects.urls')),
    path('project/', include('django.contrib.auth.urls')),
    path('test_runs/', include('test_runs.urls')),
    path('test_runs/', include('django.contrib.auth.urls')),
    path('weekly_reports/', include('weekly_reports.urls')),
    path('weekly_reports/', include('django.contrib.auth.urls')),
    path('djrichtextfield/', include('djrichtextfield.urls')),
    path('', include('dashboard.urls')),
]

tms/devices/models.py
from django.db import models
from simple_history.models import HistoricalRecords

from base.base import DEVICE_PLATFORM, DEVICE_PLATFORM_ANDROID, DEVICE_STATUS_CHOICES, DEVICE_STATUS_AVAILABLE
from django.conf import settings


class Device(models.Model):
    name = models.CharField(max_length=20)
    description = models.CharField(max_length=200)
    sn = models.CharField(max_length=20)
    created_date = models.DateTimeField('date created', auto_now_add=True, blank=True)
    upd_date = models.DateTimeField('date updated', auto_now=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, default=None, blank=True)

    os_version = models.CharField(max_length=10)
    device_platform = models.IntegerField(choices=DEVICE_PLATFORM, default=DEVICE_PLATFORM_ANDROID)

    device_status = models.IntegerField(choices=DEVICE_STATUS_CHOICES, default=DEVICE_STATUS_AVAILABLE)

    history = HistoricalRecords()

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'device_tab'

tms/devices/forms.py
# Django
from django import forms
# Local
from .models import Device


class DeviceForm(forms.ModelForm):
    class Meta:
        model = Device
        exclude = ['timestamp']

tms/devices/views.py
from django.urls import reverse_lazy
from django.views import generic
from .forms import DeviceForm
from .models import Device


from django.template.defaulttags import register


@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)


class DeviceOverviewView(generic.DetailView):
    model = Device
    template_name = 'devices/device_overview.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['does_enter_a_project'] = False
        return context


class DeviceCreateView(generic.CreateView):
    template_name = 'devices/create_device.html'
    form_class = DeviceForm
    success_url = reverse_lazy('dashboard')


class DeviceUpdateView(generic.UpdateView):
    model = Device
    template_name = 'devices/update_device.html'
    form_class = DeviceForm
    success_url = reverse_lazy('dashboard')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['does_enter_a_project'] = False
        return context


class DeviceReadView(generic.DetailView):
    model = Device
    template_name = 'devices/read_device.html'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['does_enter_a_device'] = True
    #     return context


class DeviceDetailView(generic.DetailView):
    model = Device
    template_name = 'devices/device_detail.html'

    def get_context_data(self, **kwargs):
        pk = self.kwargs.get("pk")
        device = Device.objects.get(pk=pk)
        context = super().get_context_data(**kwargs)
        context['does_enter_a_project'] = False
        context['GLOBAL_PROJECT_ID'] = device.pk
        context['GLOBAL_PROJECT_NAME'] = device.name
        return context


class DeviceDeleteView(generic.DeleteView):
    model = Device
    template_name = 'devices/delete_device.html'
    success_url = reverse_lazy('dashboard')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['does_enter_a_project'] = False
        return context


class DeviceIndex(generic.ListView):
    model = Device
    context_object_name = 'devices'
    template_name = 'devices/device_index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        devices = Device.objects.all()
        context['all_devices_list'] = devices
        context['does_enter_a_project'] = False
        return context

tms/templates/devices/create_device.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Create Device</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-primary" formnovalidate="formnovalidate">Create</button>
  </div>

</form>

tms/templates/devices/delete_device.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Delete Device</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p>Are you sure you want to delete Device
      <strong>{{ device.name }} ({{ device.sn }})</strong>?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-danger" formnovalidate="formnovalidate">Delete</button>
  </div>

</form>

tms/templates/devices/device_index.html
{% extends 'base/base_modal.html' %}
{% load menu %}
{% block content %}
{% generate_menu %}
{% if not user.is_anonymous %}
<div class="container mt-3">
    <div class="row">
        <div class="col">
            {% include "base/menu.html" %}
            <h4>
                <strong>Device List</strong>
            </h4>
            <div class="row">
                <div class="col-12 mb-3">
                    <button class="create-device btn btn-primary" type="button" name="button">
                        <span class="fa fa-plus mr-2"></span>Create Device
                    </button>
                </div>

                
                <div class="col-12 mb-3">
                    {% if devices %}
                    <table class="table">
                        <thead>
                        <tr>
                            <th class="text-center" scope="col">#</th>
                            <th class="text-center" scope="col">Name</th>
                            <th class="text-center" scope="col">Description</th>
                            <th class="text-center" scope="col">Serial Number</th>
                            <th class="text-center" scope="col">OS Version</th>
                            <th class="text-center" scope="col">Platform</th>
                            <th class="text-center" scope="col">Status</th>
                            <th class="text-center" scope="col">Keeper</th>
                            <th class="text-center" scope="col">Read / Update / Delete</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for device in devices %}
                        <tr>
                            <th class="text-center" scope="row">{{ forloop.counter }}</th>
                            <td class="text-center">{{ device.name }}</td>
                            <td class="text-center">{{ device.description }}</td>
                            <td class="text-center">{{ device.sn }}</td>
                            <td class="text-center">{{ device.os_version }}</td>
                            <td class="text-center">{{ device.get_device_platform_display }}</td>
                            <td class="text-center">{{ device.get_device_status_display }}</td>
                            <td class="text-center">{{ device.user }}</td>
                            <td class="text-center">
                                <button type="button" class="update-device btn btn-sm btn-primary"
                                        data-id="{% url 'devices:read_device' device.pk %}">
                                    <span class="fa fa-eye"></span>
                                </button>
                                <button type="button" class="update-device btn btn-sm btn-primary"
                                        data-id="{% url 'devices:update_device' device.pk %}">
                                    <span class="fa fa-pencil"></span>
                                </button>
                                <button type="button" class="delete-device btn btn-sm btn-danger"
                                        data-id="{% url 'devices:delete_device' device.pk %}">
                                    <span class="fa fa-trash" aria-label="Delete"></span>
                                </button>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    {% else %}
                    <p class="text-primary">No device added yet.</p>
                    {% endif %}
                </div>
            </div>

        </div>
    </div>

    {% endif %}
    {% endblock content %}

    {% block extrascripts %}
    <script type="text/javascript">
    $(function () {
      // Log in & Sign up buttons
      $(".login-btn").modalForm({formURL: "{% url 'login' %}", successURL: "/"});

      // Create device button
      $(".create-device").modalForm({formURL: "{% url 'devices:create_device' %}", successURL: "{% url 'devices:device_overview' %}"});

      // Update device buttons
      $(".update-device").each(function () {
        $(this).modalForm({formURL: $(this).data('id'), successURL: "{% url 'devices:device_overview' %}"});
      });

      // Delete device buttons
      $(".delete-device").each(function () {
        $(this).modalForm({formURL: $(this).data('id'), successURL: "{% url 'devices:device_overview' %}"});
      });

    });






    </script>
    {% endblock extrascripts %}

tms/templates/devices/read_device.html
{% load widget_tweaks %}

<div class="modal-header">
  <h3 class="modal-title">Device Details</h3>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<div class="modal-body">

  <div class=""><strong>Name</strong>: {{ device.name }}</div>
  <div class=""><strong>Description</strong>: {{ device.description }}</div>
  <div class=""><strong>Serial Number</strong>: {{ device.sn }}</div>
  <div class=""><strong>OS Version</strong>: {{ device.os_version }}</div>
  <div class=""><strong>Platform</strong>: {{ device.get_device_platform_display }}</div>
  <div class=""><strong>Status</strong>: {{ device.get_device_status_display }}</div>
  <div class=""><strong>Keeper</strong>: {{ device.user }}</div>
  <div class=""><strong>Created Date</strong>: {{ device.created_date }}</div>
  <div class=""><strong>Updated Date</strong>: {{ device.upd_date }}</div>

</div>

<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>

tms/templates/devices/update_device.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Update Device</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-primary" formnovalidate="formnovalidate">Update</button>
  </div>

</form>