tms/books/urls.py
# Django
from django.urls import path
# Local
from books import views

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('create/', views.BookCreateView.as_view(), name='create_book'),
    path('update/<int:pk>', views.BookUpdateView.as_view(), name='update_book'),
    path('read/<int:pk>', views.BookReadView.as_view(), name='read_book'),
    path('delete/<int:pk>', views.BookDeleteView.as_view(), name='delete_book')
]

tms/tms/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('news/', include('news.urls')),
    path('news/', include('django.contrib.auth.urls')),
    path('test_cases/', include('test_cases.urls')),
    path('test_cases/', include('django.contrib.auth.urls')),
    path('device/', include('devices.urls')),
    path('device/', include('django.contrib.auth.urls')),
    path('project/', include('projects.urls')),
    path('project/', include('django.contrib.auth.urls')),
    path('test_runs/', include('test_runs.urls')),
    path('test_runs/', include('django.contrib.auth.urls')),
    path('weekly_reports/', include('weekly_reports.urls')),
    path('weekly_reports/', include('django.contrib.auth.urls')),
    path('djrichtextfield/', include('djrichtextfield.urls')),
    path('', include('dashboard.urls')),
]

tms/books/models.py
# Django
from django.db import models


class Book(models.Model):
    HARDCOVER = 1
    PAPERBACK = 2
    EBOOK = 3
    BOOK_TYPES = (
        (HARDCOVER, 'Hardcover'),
        (PAPERBACK, 'Paperback'),
        (EBOOK, 'E-book'),
    )
    title = models.CharField(max_length=50)
    publication_date = models.DateField(null=True)
    author = models.CharField(max_length=30, blank=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    pages = models.IntegerField(blank=True, null=True)
    book_type = models.PositiveSmallIntegerField(choices=BOOK_TYPES)

    timestamp = models.DateField(auto_now_add=True, auto_now=False)

tms/books/forms.py
# Django
from django import forms
# Local
from .models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        exclude = ['timestamp']

tms/books/views.py
# Django
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
# Local
from .forms import BookForm
from .models import Book


class Index(generic.ListView):
    model = Book
    context_object_name = 'books'
    template_name = 'index.html'


class BookCreateView(generic.CreateView):
    template_name = 'books/create_book.html'
    form_class = BookForm
    success_url = reverse_lazy('index')


class BookUpdateView(generic.UpdateView):
    model = Book
    template_name = 'books/update_book.html'
    form_class = BookForm
    success_url = reverse_lazy('index')


class BookReadView(generic.DetailView):
    model = Book
    template_name = 'books/read_book.html'


class BookDeleteView(generic.DeleteView):
    model = Book
    template_name = 'books/delete_book.html'
    success_url = reverse_lazy('index')

tms/templates/books/create_book.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Create Book</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-primary" formnovalidate="formnovalidate">Create</button>
  </div>

</form>

tms/templates/books/delete_book.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Delete Book</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p>Are you sure you want to delete book with title
      <strong>{{ book.title }}</strong>?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-danger" formnovalidate="formnovalidate">Delete</button>
  </div>

</form>

tms/templates/books/read_book.html
{% load widget_tweaks %}

<div class="modal-header">
  <h3 class="modal-title">Book details</h3>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<div class="modal-body">

  <div class="">
    Title:
    {{ book.title }}
  </div>
  <div class="">
    Author:
    {{ book.author }}
  </div>
  <div class="">
    Type:
    {{ book.get_book_type_display }}
  </div>
  <div class="">
    Publication date:
    {{ book.publication_date }}
  </div>
  <div class="">
    Pages:
    {{ book.pages }}
  </div>
  <div class="">
    Price:
    {{ book.price }}
  </div>

</div>

<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>

tms/templates/books/update_book.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Update Book</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-primary" formnovalidate="formnovalidate">Update</button>
  </div>

</form>